### ISSUE TITLE
How to speed up?

### ISSUE THREAD

**Issue by applenob** [opendilab/Gobigger-Explore#15]
Hi, 
nice baseline repo!
Your log of v0.3 shows that it takes more than 3 days to train this model.
I have tried to use ddp to speed up the training process but still not satisfied.
Do you have any suggestion for speeding the training process up in a multi-gpu and high-memory machine? Any useful params to share?

**Comment by jayyoung0802** [comment]
1.Maybe DP can help you, but you just use DP in Encoder model.
2.Version 0.3 take less resources and get lower performance than v0.2. 
3.We will release new version this week, and its model and  feature engineering maybe can help you. https://github.com/opendilab/Gobigger-Explore/pull/16
