### ISSUE TITLE
when I use Multi-GPUs to train my model，RuntimeError: Caught RuntimeError in replica 0 on device 0

### ISSUE THREAD

**Issue by zyegao** [opendilab/Gobigger-Explore#3]
When I test the DP mode ,the error happened 
![image](https://user-images.githubusercontent.com/15649422/147053519-a6cc55b5-6d23-40ab-9ad0-3383d7a161c1.png)

Refer to the https://di-engine-docs.readthedocs.io/zh_CN/latest/best_practice/multi_gpu_example.html， I changed the file：
（1）gobigger_no_spatial_config.py
![image](https://user-images.githubusercontent.com/15649422/147053724-8a16384e-e90a-4b45-a0c1-6a3f81e637ec.png)
（2）gobigger_vsbot_baseline_simple_main.py
![image](https://user-images.githubusercontent.com/15649422/147053776-4d8f2942-caa6-48dd-8344-5cc5846a4e4c.png)

**Comment by jayyoung0802** [comment]
Regarding this issue, we have summarized the following points
1、[3, 3, 16] is [evaluator_num, players_per_team, 4*4(dirction * action)]
2、In policy, we merge the first two dimensions, so it becomes [9,16].
3、When using DP，it will divide 9 into 4 and 5, and it will becomes [4,16] and [5,16].
4、[4,16] and [5,16]  can't transform [batch, 3, 16], So it reported an error.
5、The solution is to **only use DP on _Encode_，not on all gobigger model.**
