### ISSUE TITLE
能否提供一个官方的打包程序，就像1.0的test.py一样

### ISSUE THREAD

**Issue by Rinstein** [opendilab/Gobigger-Explore#7]

**Comment by jayyoung0802** [comment]
Sorry to reply to you so late, this part needs to be implemented by the player, we only provide a simple example.
The test.py is the same as the previous version, you need to modify the "mysubmission" according to your own design.
For example, not the only 
`
  class MyAgent:   # Your Agent
      def __init__(self, team_name, player_names):
          self.team_name = team_name
          self.player_names = player_names
          self.ckpt_path = ''
          self.model = Model()  # need to load ckpt_path
          self.policy = Policy()
      def action(obs):
           pass
  class MySubmission(BaseSubmission):
      def __init__(self, team_name, player_names):
          super(MySubmission, self).__init__(team_name, player_names)
          self.agent = MyAgent(team_name, player_names)  
      def get_actions(self, obs):
          global_state, player_states = obs
          actions = {}
          for player_name, _ in player_states.items():
              action = self.agent.action(obs)   # obs need to process
              actions[player_name] = action
          return actions
`
Please note the comment section！

**Comment by Rinstein** [comment]
okay, get it, thx.
